# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Config-Validate
version:      0.1.0
version_from: lib/Config/Validate.pm
installdirs:  site
requires:
    Carp::Clan:                    0
    Data::Validate::Domain:        0
    Object::InsideOut:             0
    Params::Validate:              0
    Scalar::Util::Clone:           0
    Test::Class:                   0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
